#[test]
fn cargo_dist_targets_cover_primary_desktop_and_server_platforms() {
    let cargo = std::fs::read_to_string("Cargo.toml").unwrap();
    for target in [
        "aarch64-apple-darwin",
        "x86_64-apple-darwin",
        "x86_64-unknown-linux-gnu",
        "x86_64-pc-windows-msvc",
    ] {
        assert!(cargo.contains(target), "missing cargo-dist target {target}");
    }
    assert!(cargo.contains("installers"));
    assert!(cargo.contains("npm"));
    assert!(cargo.contains("[profile.dist]"));
    assert!(cargo.contains("inherits = \"release\""));
    assert!(cargo.contains("[workspace.metadata.dist.github-custom-runners]"));
    assert!(cargo.contains("aarch64-apple-darwin = \"macos-15\""));
    assert!(cargo.contains("x86_64-apple-darwin = \"macos-15-intel\""));
}

#[test]
fn release_workflow_uses_generated_cargo_dist_artifact_flow() {
    let workflow = std::fs::read_to_string(".github/workflows/release.yml").unwrap();
    assert!(workflow.contains("This file was autogenerated by dist"));
    assert!(workflow.contains("cargo-dist/releases/download/v0.30.0/cargo-dist-installer.sh"));
    assert!(workflow.contains("runs-on: \"ubuntu-22.04\""));
    assert!(workflow.contains("persist-credentials: false"));
    assert!(workflow.contains("host --steps=create --tag={0}"));
    assert!(workflow.contains("artifacts-matrix: ${{ steps.plan.outputs.artifacts-matrix }}"));
    assert!(workflow.contains("has-local-artifacts: ${{ steps.plan.outputs.has-local-artifacts }}"));
    assert!(workflow.contains(
        "if: ${{ needs.plan.outputs.has-local-artifacts == 'true' && (needs.plan.outputs.publishing == 'true' || needs.plan.outputs.pr-run-mode == 'upload') }}"
    ));
    assert!(workflow.contains("matrix: ${{ fromJson(needs.plan.outputs.artifacts-matrix) }}"));
    assert!(workflow.contains("dist build ${{ needs.plan.outputs.tag-flag }} --print=linkage --output-format=json ${{ matrix.dist_args }}"));
    assert!(workflow.contains(
        "dist build ${{ needs.plan.outputs.tag-flag }} --output-format=json \"--artifacts=global\""
    ));
    assert!(workflow.contains("actions/upload-artifact@v4"));
    assert!(workflow.contains("actions/download-artifact@v4"));
    assert!(workflow.contains("gh release create"));
}
